serviceMaps:
  serviceName: death-services
  mappings:   
      
  - version: 1.0
    description: Persists death reporting form details in eg_death_dtls_registry,eg_death_statistical_registry,eg_death_address_registry  table by rakhi s ikm on 10.02.2023
    fromTopic: save-deathregistrydetails-topic
    isTransaction: true
    queryMaps:

    - query: INSERT INTO public.eg_death_dtls_registry(id, registrationunit, tenantid, dateofdeath, time_of_death, timeofdeath_unit, death_place, death_place_inst_type, death_place_inst_id, deceased_firstname_en, deceased_firstname_ml, deceased_middlename_en, deceased_middlename_ml, deceased_lastname_en, deceased_lastname_ml, deceased_aadhar_unavailable, deceased_aadhar_number, deceased_gender, age, age_unit, informant_name_en, informant_aadhar_submitted, informant_aadhar_no, informant_mobile_no, general_remarks, application_status, created_by, createdtime, lastmodifiedby, lastmodifiedtime, registration_no, male_dependent_name_en, male_dependent_name_ml, male_dependent_aadharno, female_dependent_name_en, female_dependent_name_ml, female_dependent_aadharno,  vehicle_hospital_en, vehicle_fromplace_ml, vehicle_fromplace_en, vehicle_toplace_ml, vehicle_toplace_en, vehicle_number, death_place_ward_id, death_signed_officer_designation, deceased_idprooftype, application_no, file_no, ack_no, registration_date, registration_no_id, deceased_idproofno, vehicle_first_halt, vehicle_first_halt_ml, male_dependent_unavailable, female_dependent_unavailable, spouse_name_en, spouse_name_ml, spouse_unavailable, spouse_aadhaar, spouse_type, funcion_uid, death_place_locality_en, death_place_locality_ml, death_place_street_en, death_place_street_ml, death_place_country, death_place_state, death_place_district, death_place_city, death_place_remarks_en, death_place_remarks_ml, place_of_burial_en, place_of_burial_ml, death_home_locality_en, death_home_locality_ml, death_home_street_en, death_home_street_ml, death_home_housename_en, death_home_housename_ml, death_home_postoffice_id, death_home_pincode, death_home_ward, 
          death_home_taluk_id, certificate_no_id, certificate_no, certificate_date ,informant_address ,is_declaration_informant)
          VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
     

      basePath: deathCertificateDtls.*
      jsonMaps:
      - jsonPath: $.deathCertificateDtls.*.InformationDeath.Id

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.RegistrationUnit

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.TenantId

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DateOfDeath

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.TimeOfDeath

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.TimeOfDeathUnit

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlace

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceType

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceInstId

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeceasedFirstNameEn

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeceasedFirstNameMl

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeceasedMiddleNameEn

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeceasedMiddleNameMl

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeceasedLastNameEn

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeceasedLastNameMl

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeceasedAadharNotAvailable

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeceasedAadharNumber

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeceasedGender

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.Age

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.AgeUnit

      - jsonPath: $.deathCertificateDtls.*.InformantDetails.InformantNameEn

      - jsonPath: $.deathCertificateDtls.*.InformantDetails.InformantAadharSubmitted

      - jsonPath: $.deathCertificateDtls.*.InformantDetails.InformantAadharNo

      - jsonPath: $.deathCertificateDtls.*.InformantDetails.InformantMobileNo

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.GeneralRemarks

      - jsonPath: $.deathCertificateDtls.*.applicationStatus

      - jsonPath: $.deathCertificateDtls.*.AuditDetails.createdBy
      
      - jsonPath: $.deathCertificateDtls.*.AuditDetails.createdTime

      - jsonPath: $.deathCertificateDtls.*.AuditDetails.lastModifiedBy

      - jsonPath: $.deathCertificateDtls.*.AuditDetails.lastModifiedTime

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.registrationNo

      - jsonPath: $.deathCertificateDtls.*.FamilyInformationDeath.FatherNameEn

      - jsonPath: $.deathCertificateDtls.*.FamilyInformationDeath.FatherNameMl

      - jsonPath: $.deathCertificateDtls.*.FamilyInformationDeath.FatherAadharNo

      - jsonPath: $.deathCertificateDtls.*.FamilyInformationDeath.MotherNameEn

      - jsonPath: $.deathCertificateDtls.*.FamilyInformationDeath.MotherNameMl

      - jsonPath: $.deathCertificateDtls.*.FamilyInformationDeath.MotherAadharNo

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.VehicleHospitalEn

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.VehicleFromplaceMl

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.VehicleFromplaceEn

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.VehicleToPlaceMl

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.VehicleToPlaceEn

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.VehicleNumber

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceWardId

      - jsonPath: $.deathCertificateDtls.*.InformantDetails.DeathSignedOfficerDesignation

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeceasedIdproofType

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathApplicationNo

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.fileNo

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathACKNo      

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.RegistrationDate

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.registrationNoID

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeceasedIdproofNo

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.VehicleFirstHaltEn

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.VehicleFirstHaltMl

      - jsonPath: $.deathCertificateDtls.*.FamilyInformationDeath.FatherUnavailable

      - jsonPath: $.deathCertificateDtls.*.FamilyInformationDeath.MotherUnavailable

      - jsonPath: $.deathCertificateDtls.*.FamilyInformationDeath.SpouseNameEn

      - jsonPath: $.deathCertificateDtls.*.FamilyInformationDeath.SpouseNameML

      - jsonPath: $.deathCertificateDtls.*.FamilyInformationDeath.SpouseUnavailable

      - jsonPath: $.deathCertificateDtls.*.FamilyInformationDeath.SpouseAadhaar

      - jsonPath: $.deathCertificateDtls.*.FamilyInformationDeath.SpouseType

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.funcionUID

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceLocalityEn

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceLocalityMl

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceStreetEn

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceStreetMl

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceCountry

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceState

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceDistrict

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceCity

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceRemarksEn

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceRemarksMl

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.PlaceOfBurialEn

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.PlaceOfBurialMl    

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceHomeLocalityEn

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceHomeLocalityMl

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceHomeStreetNameEn

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceHomeStreetNameMl

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceHomeHoueNameEn

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceHomeHoueNameMl

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceHomePostofficeId

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceHomePincode

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceHomeWardId

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.DeathPlaceHomeTalukId

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.certificateNoId

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.certificateNo

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.certificateDate

      - jsonPath: $.deathCertificateDtls.*.InformantDetails.InformantAddress

      - jsonPath: $.deathCertificateDtls.*.InformantDetails.IsDeclarationInformant

    - query: INSERT INTO public.eg_death_address_registry(id, death_dtl_id, tenantid, addr_typeid, streetname_en, streetname_ml, locality_en, locality_ml, ward_id, taluk_id, village_id, postoffice_id, pincode, district_id, state_id, country_id, createdby, createdtime, lastmodifiedby, lastmodifiedtime, location_type, housename_ml, housename_en, lbtype, postal_code)
          VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
     

      basePath: deathCertificateDtls.*
      jsonMaps:
      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PresentAddrId

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.Id

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.TenantId

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PresentAddrTypeId

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PresentAddrStreetNameEn

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PresentAddrStreetNameMl

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PresentAddrLocalityEn

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PresentAddrLocalityMl

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PresentAddrWardId

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PresentAddrTalukId

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PresentAddrVillageId

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PresentAddrPostofficeId

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PresentAddrPincode

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PresentAddrDistrictId

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PresentAddrStateId

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PresentAddrCountryId

      - jsonPath: $.deathCertificateDtls.*.AuditDetails.createdBy
      
      - jsonPath: $.deathCertificateDtls.*.AuditDetails.createdTime

      - jsonPath: $.deathCertificateDtls.*.AuditDetails.lastModifiedBy

      - jsonPath: $.deathCertificateDtls.*.AuditDetails.lastModifiedTime

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PresentAddrLocationType

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PresentAddrHoueNameMl

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PresentAddrHoueNameEn

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrLbType

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PresentAddrPostalCode

    - query: INSERT INTO public.eg_death_address_registry(id, death_dtl_id, tenantid, addr_typeid, streetname_en, streetname_ml, locality_en, locality_ml, ward_id, taluk_id, village_id, postoffice_id, pincode, district_id, state_id, country_id, createdby, createdtime, lastmodifiedby, lastmodifiedtime, location_type, housename_ml, housename_en, lbtype, postal_code)
          VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
     

      basePath: deathCertificateDtls.*
      jsonMaps:
      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrId
      
      - jsonPath: $.deathCertificateDtls.*.InformationDeath.Id

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.TenantId

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrTypeId

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrStreetNameEn

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrStreetNameMl

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrLocalityEn

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrLocalityMl

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrWardId

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrTalukId

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrVillageId

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrPostofficeId

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrPincode

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrDistrictId

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrStateId

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrCountryId

      - jsonPath: $.deathCertificateDtls.*.AuditDetails.createdBy
      
      - jsonPath: $.deathCertificateDtls.*.AuditDetails.createdTime

      - jsonPath: $.deathCertificateDtls.*.AuditDetails.lastModifiedBy

      - jsonPath: $.deathCertificateDtls.*.AuditDetails.lastModifiedTime

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrLocationType

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrHoueNameMl

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrHoueNameEn

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrLbType

      - jsonPath: $.deathCertificateDtls.*.AddressBirthDetails.PermanentAddrPostalCode

    - query: INSERT INTO public.eg_death_statistical_registry(id, death_dtl_id, tenantid, religion, occupation, medical_attention_type, death_medically_certified, death_cause_main, death_cause_sub, death_cause_other, death_during_delivery, createdby, createdtime, lastmodifiedby, lastmodifiedtime, nationality,  smoking_type, tobacco_type,  alcohol_type, autopsy_performed, autopsy_completed, manner_of_death, death_cause_main_custom, death_cause_main_interval, death_cause_main_timeunit, death_cause_sub_custom, death_cause_sub_interval, death_cause_sub_timeunit, death_cause_sub2, death_cause_sub2_custom, death_cause_sub2_interval, death_cause_sub2_timeunit, deceased_pregnant, is_delivery)
          VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
     

      basePath: deathCertificateDtls.*
      jsonMaps:
      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.StatisticalId
      
      - jsonPath: $.deathCertificateDtls.*.InformationDeath.Id

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.TenantId

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.Religion

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.Occupation

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.MedicalAttentionType

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.DeathMedicallyCertified

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.DeathCauseMain

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.DeathCauseSub

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.DeathCauseOther

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.DeathDuringDelivery

      - jsonPath: $.deathCertificateDtls.*.AuditDetails.createdBy
      
      - jsonPath: $.deathCertificateDtls.*.AuditDetails.createdTime

      - jsonPath: $.deathCertificateDtls.*.AuditDetails.lastModifiedBy

      - jsonPath: $.deathCertificateDtls.*.AuditDetails.lastModifiedTime

      - jsonPath: $.deathCertificateDtls.*.InformationDeath.Nationality

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.SmokingType

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.TobaccoType

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.AlcoholType

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.IsAutopsyPerformed

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.IsAutopsyCompleted

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.MannerOfDeath

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.DeathCauseMainCustom

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.DeathCauseMainInterval

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.DeathCauseMainTimeUnit

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.DeathCauseSubCustom

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.DeathCauseSubInterval

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.DeathCauseSubTimeUnit

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.DeathCauseSub2

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.DeathCauseSubCustom2

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.DeathCauseSubInterval2

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.DeathCauseSubTimeUnit2

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.IsdeceasedPregnant

      - jsonPath: $.deathCertificateDtls.*.StatisticalInfo.IsDelivery
